### ISSUE TITLE
FR: Support pasting an SVG directly into the plugin window

### ISSUE THREAD

**Issue by Nek-12** [ComposeGears/Valkyrie#101]
Figma has a useful ability to copy a layer as an SVG to the clipboard. With Valkyrie, to generate an icon, a file must exist. To simplify the process of exporting a single icon, add an option to paste into the plugin window. It should be a button ("From clipboard") and a response to Ctrl+V into the window. If the clipboard content is an XML or SVG, generate an icon.

**Comment by egorikftp** [comment]
I have an idea for full integration with Figma to export icons from specific layer or board. Clipboard feature can be an first part of this huge task 🙂

**Comment by egorikftp** [comment]
Will be available in 0.10.0 release
