### ISSUE TITLE
Consider providing a CLI to use

### ISSUE THREAD

**Issue by Goooler** [ComposeGears/Valkyrie#25]
We can use it like

```sh
valkyrie --avd2iv path/to/input path/to/output
valkyrie --svg2iv path/to/input path/to/output
```

I finished this feature in https://github.com/DevSrSouza/svg-to-compose/pull/22, related issue in https://github.com/DevSrSouza/svg-to-compose/issues/23. , be willing to send a PR here.

**Comment by egorikftp** [comment]
@Goooler Hello, I saw that you made some implementation in a separate branch 🤩 
Do you have plans to release a CLI tool?

**Comment by Goooler** [comment]
Yeah, I need to add some tests before that.
