### ISSUE TITLE
SVG with 'clip-path' parse incorrectly

### ISSUE THREAD

**Issue by StefanOltmann** [ComposeGears/Valkyrie#314]
Hi,

I found that Valkyrie has troubles converting [this SVG](https://github.com/user-attachments/assets/58541dfd-e334-4a95-8971-c81fadda35a6) to something that looks the same.

Kind regards,

Stefan

**Comment by egorikftp** [comment]
Hello, thanks for example
Will check soon

**Comment by StefanOltmann** [comment]
Great, thank you. :)

I tried to change the inputs by ![minifying the SVG](https://github.com/user-attachments/assets/c2cf47d6-6a50-4a21-9208-8363052a0a4e) and inputing XML, but the result is always the same.

**Comment by egorikftp** [comment]
Issue related to `clip-path` parsing 

Will push fix soon
![Image](https://github.com/user-attachments/assets/787f9f13-4b8f-4534-8baa-c4ea371ca503)

**Comment by egorikftp** [comment]
Available in 0.11.1
