### ISSUE TITLE
OOM when generating IconPack using the dir contains huge SVG files

### ISSUE THREAD

**Issue by Goooler** [ComposeGears/Valkyrie#36]
Open `IconPack` and set the other options, then pick dir as input, no response occurs. ~~I remember this behavior works on my x64 Mac, but it's not working on Apple Silicon Mac now.~~ OOM related issues  have been reported from IDEA:

```
The IDE ran out of available memory. Please consider increasing the value of "Maximum Heap Size" setting.
``` 

I can repro this from market version 0.3.0 and 0.3.1 from the latest build, and they are not working for IDEA 2024.1, 2024.2 Beta, and AS 2024.1.3.

https://github.com/user-attachments/assets/13def298-b4be-4e6d-9798-34d70fa7ca1d

**Comment by Goooler** [comment]
The root cause is OOM, there are 5500+ SVG files under https://github.com/LawnchairLauncher/lawnicons/tree/develop/svgs

<img width="575" alt="image" src="https://github.com/user-attachments/assets/0360cfc1-c94a-4843-b087-3d239697e192">

**Comment by egorikftp** [comment]
Nice case 😄 
Will see what we can do. Maybe OOM reason is creating `Painter`

https://github.com/ComposeGears/Valkyrie/blob/3c7573f62d5a3988be1202269424c7bf71758074/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/conversion/util/FileToPainter.kt#L13

**Comment by egorikftp** [comment]
yes, it's a reason

https://github.com/user-attachments/assets/52c2d389-e7fe-45f7-a5f0-adf73d3952eb
