### ISSUE TITLE
Create draft nightly releases on GitHub

### ISSUE THREAD

**Issue by egorikftp** [ComposeGears/Valkyrie#39]
Reference: 
https://github.com/LawnchairLauncher/lawnchair/blob/9b74fe86e0ef2e1088edc025b7bec40fcbb52784/.github/workflows/ci.yml#L122-L141

_Originally posted by @Goooler in https://github.com/ComposeGears/Valkyrie/issues/37#issuecomment-2242705533_

**Comment by Goooler** [comment]
I'll send a PR later.
