### ISSUE TITLE
Extend available quick actions in the IDE

### ISSUE THREAD

**Issue by Nek-12** [ComposeGears/Valkyrie#47]
Currently for generating icons in simple mode, each file needs to be dropped into the plugin window, copied via the copy button, and then pasted into desired directory. This makes the plugin hard to use when importing, say 10 new icons to an existing icon pack. This is a feature request to support:

- [x] #175
- [x] A multi-import feature. When multiple files are dropped together into the simple mode import window, the behavior should change to let the user pick where to place the resulting Kotlin files instead of just showing the content of the first file
- [x] An "existing icon pack" toggle / field, which would allow the icon(s) to be prefixed with the icon pack `object` namespace out of the box. 
- [x] A "rename by regex" feature to reformat the names of the icon files dropped into a window to match the project conventions. E.g.: ic_flower_outline_24.svg -> FlowerOutline
- [x] A button to "save to the current package / file" to avoid copying the file contents, finding a package and pasting them to create a file.

**Comment by egorikftp** [comment]
@Nek-12 Could you please create separate issue for "rename by regex" feature with clear example how it should work?

**Comment by Nek-12** [comment]
Sure! Since you implemented the rest, I'll assume I need to close this one. Feel free to reopen if there is still something to do.
