### ISSUE TITLE
Reduced output float precision

### ISSUE THREAD

**Issue by sandboiii** [ComposeGears/Valkyrie#71]
Hey, I have a question about output precision. I tried to convert my icons with your plugin and with composables.com. The problem is that the plugin reduces the float precision in output code.

Here is the example:
I have this icon: ![like_24](https://github.com/user-attachments/assets/4b374b6a-5ab9-4f18-96e9-8a010a485bb5)

the first command in this icon is move: `M12.111 5.69952` which the site composables.com translates to this code:
```kotlin
moveTo(12.111f, 5.69952f)
```

But the plugin translates the same line to:
```kotlin
moveTo(12.111f, 5.7f)
```

Is this intended behavior of the plugin? Or it's an output formatting problem?

**Comment by egorikftp** [comment]
Hello, thanks for your interest to plugin!

Currently if you try to parse SVG, I convert it into XML drawable using `com.android.ide.common.vectordrawable.Svg2Vector` and it returns values with reduced precision.

![IMAGE 2024-07-29 14:55:18](https://github.com/user-attachments/assets/3a1727cb-1974-4061-a295-54ec52b4f2fa)

The same XML icon generated using Android Studio 

![telegram-cloud-photo-size-2-5276271545821551516-y](https://github.com/user-attachments/assets/3e79f2f9-7c99-4966-a84e-92b353511bac)

**Comment by sandboiii** [comment]
Wow, I totally did not expect that. Never thought Android Studio rounds coordinates when you add icons. Guess, there must be some reason behind that. And I'm not sure if this must be fixed or not

**Comment by egorikftp** [comment]
More debugging 🙂 
I found [line](https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-main:sdk-common/src/main/java/com/android/ide/common/vectordrawable/VdPath.java;l=186) that make this precision

<img width="983" alt="image" src="https://github.com/user-attachments/assets/6d5f2a60-0cbd-4864-aa17-e5c1f082de11">

Looks like "composables" and plugin uses different approaches to parse svg icons, but looks like it will not affect visual at all.

**Comment by vkatz** [comment]
> Wow, I totally did not expect that. Never thought Android Studio rounds coordinates when you add icons. Guess, there must be some reason behind that. And I'm not sure if this must be fixed or not

Guessing: having image 24x24 dp  - the precision step will be around 0.01 (distanse that will be visible if changed), probably it is just a precision optimizations from side of google

**Comment by sandboiii** [comment]
Ok, so this is nothing to worry about. This issue can be closed then
